/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maragarita
 */
public class PanelPersonajes extends javax.swing.JFrame {

    /**
     * Creates new form PanelPersonajes
     */
    ArrayList<Object> listaJugadores = new ArrayList<>();
    Controlador controller = new Controlador();
    
    public PanelPersonajes() {
        initComponents();
        // Centering on screen...
        setSize(528,442);
        listaJugadores=controller.extraerObjetos("jugadores.dat");
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cmbJugador1 = new javax.swing.JComboBox<>();
        cmbJugador2 = new javax.swing.JComboBox<>();
        cmbPersonajes = new javax.swing.JComboBox<>();
        btnSeleccionarJugador1 = new javax.swing.JButton();
        btnBatalla = new javax.swing.JButton();
        btnSeleccionarJugador2 = new javax.swing.JButton();
        btnRegresoRegistro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tekton Pro Cond", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 204));
        lblTitulo.setText("POO BATTLE PRO");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(150, 10, 250, 30);

        cmbJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador1);
        cmbJugador1.setBounds(10, 37, 135, 20);

        cmbJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador2);
        cmbJugador2.setBounds(366, 37, 130, 20);

        cmbPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "personaje1", "personaje2" }));
        cmbPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonajesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPersonajes);
        cmbPersonajes.setBounds(200, 70, 110, 30);

        btnSeleccionarJugador1.setText("Seleccionar jugador 1");
        btnSeleccionarJugador1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSeleccionarJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarJugador1);
        btnSeleccionarJugador1.setBounds(10, 321, 135, 23);

        btnBatalla.setText("Empezar");
        getContentPane().add(btnBatalla);
        btnBatalla.setBounds(220, 380, 80, 23);

        btnSeleccionarJugador2.setText("Seleccionar jugador 2");
        btnSeleccionarJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarJugador2);
        btnSeleccionarJugador2.setBounds(366, 321, 140, 23);

        btnRegresoRegistro.setText("Registro de Jugadores");
        btnRegresoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresoRegistroMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresoRegistro);
        btnRegresoRegistro.setBounds(60, 380, 141, 23);

        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 380, 137, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPanelPersonajes.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarJugador2ActionPerformed
        // TODO add your handling code here:
        btnSeleccionarJugador1.setEnabled(true);
    }//GEN-LAST:event_btnSeleccionarJugador2ActionPerformed

    private void cmbJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador1ActionPerformed
        // TODO add your handling code here:
        Jugador jugadorselect = (Jugador)cmbJugador1.getSelectedItem();
        
        btnSeleccionarJugador2.setEnabled(false);
        
        
    }//GEN-LAST:event_cmbJugador1ActionPerformed

    private void btnRegresoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresoRegistroMouseClicked
        // TODO add your handling code here:
        Juego jugadores=new Juego();
        jugadores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresoRegistroMouseClicked

    private void btnSeleccionarJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarJugador1ActionPerformed
        // TODO add your handling code here:
        
        
        btnSeleccionarJugador2.setEnabled(true);
    }//GEN-LAST:event_btnSeleccionarJugador1ActionPerformed

    private void cmbJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador2ActionPerformed
        // TODO add your handling code here:
         Jugador jugadorselect = (Jugador)cmbJugador1.getSelectedItem();
        
        btnSeleccionarJugador1.setEnabled(false);
        
    }//GEN-LAST:event_cmbJugador2ActionPerformed

    private void cmbPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPersonajesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          VentanaInicial menu= new VentanaInicial();
            menu.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPersonajes().setVisible(true);
            }
        });
    }
    public void llenarCombo(){
        if(listaJugadores.size() > 0){
            cmbJugador1.setEnabled(true);
            cmbJugador2.setEnabled(true);
           
            cmbJugador1.setModel(new javax.swing.DefaultComboBoxModel(listaJugadores.toArray()));
            cmbJugador2.setModel(new javax.swing.DefaultComboBoxModel(listaJugadores.toArray()));
      
        }else{
            cmbJugador1.setEnabled(false);
            
            cmbJugador2.setEnabled(false);
        }
    }
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalla;
    private javax.swing.JButton btnRegresoRegistro;
    private javax.swing.JButton btnSeleccionarJugador1;
    private javax.swing.JButton btnSeleccionarJugador2;
    private javax.swing.JComboBox<String> cmbJugador1;
    private javax.swing.JComboBox<String> cmbJugador2;
    private javax.swing.JComboBox<String> cmbPersonajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
