/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public final class Juego extends javax.swing.JFrame {

    ArrayList<Object> jugadores = new ArrayList<>();
    Controlador controller = new Controlador();
    
    
    
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();

        jugadores = controller.extraerObjetos("jugadores.dat");
        System.out.println(jugadores.size());
        llenarCombo();
        llenarGrid();
        if (jugadores.size() > 0) {
            Jugador ultimo = (Jugador) jugadores.get(jugadores.size() - 1);

        }

        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbListaJugadores = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaJugadores = new javax.swing.JTable();
        btnCambiarPanel = new javax.swing.JButton();
        jblTitulo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 255, 204));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre);
        lblNombre.setBounds(40, 80, 60, 17);

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(51, 255, 204));
        lblApellido.setText("Apellido:");
        jPanel1.add(lblApellido);
        lblApellido.setBounds(40, 120, 53, 17);

        lblCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(51, 255, 204));
        lblCedula.setText("Cédula:");
        jPanel1.add(lblCedula);
        lblCedula.setBounds(40, 160, 53, 20);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 255, 204));
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(40, 200, 53, 20);

        txtNombreUsuario.setMinimumSize(new java.awt.Dimension(6, 25));
        jPanel1.add(txtNombreUsuario);
        txtNombreUsuario.setBounds(100, 70, 110, 30);

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido);
        txtApellido.setBounds(100, 110, 110, 30);

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula);
        txtCedula.setBounds(100, 150, 110, 30);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(100, 190, 110, 30);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(280, 150, 90, 80);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);
        btnCrear.setBounds(370, 70, 90, 80);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(460, 150, 90, 80);

        cmbListaJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaJugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(cmbListaJugadores);
        cmbListaJugadores.setBounds(230, 30, 132, 30);

        tblListaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Usuario", "Victorias"
            }
        ));
        jScrollPane2.setViewportView(tblListaJugadores);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 260, 400, 151);

        btnCambiarPanel.setText("Seleccion Personajes");
        btnCambiarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarPanelMouseClicked(evt);
            }
        });
        btnCambiarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPanelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarPanel);
        btnCambiarPanel.setBounds(420, 260, 160, 70);

        jblTitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(51, 255, 204));
        jblTitulo.setText("Jugadores");
        jPanel1.add(jblTitulo);
        jblTitulo.setBounds(144, 35, 83, 20);

        btnMenu.setText("Menu Principal");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(420, 346, 160, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRegistro1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 420);

        jTabbedPane1.addTab("REGISTRAR", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPanelActionPerformed
        // TODO add your handling code here:
        if (jugadores.size() > 1) {
            PanelPersonajes personajes = new PanelPersonajes();
            personajes.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Registre al menos 2 jugadores");
        }
    }//GEN-LAST:event_btnCambiarPanelActionPerformed

    private void btnCambiarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarPanelMouseClicked

    private void cmbListaJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaJugadoresActionPerformed
        // TODO add your handling code here:
        Jugador jugadorselect = (Jugador) cmbListaJugadores.getSelectedItem();

        txtCedula.setText(jugadorselect.getCedula());
        txtNombreUsuario.setText(jugadorselect.getNombre());
        txtApellido.setText(jugadorselect.getApellido());
        txtUsuario.setText(jugadorselect.getLogin());

        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCrear.setEnabled(false);
    }//GEN-LAST:event_cmbListaJugadoresActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        Jugador jugSeleccionado = (Jugador) cmbListaJugadores.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblListaJugadores.getModel();
        //System.out.println(cmbestudiantes.getSelectedIndex());
        model.removeRow(cmbListaJugadores.getSelectedIndex());
        jugadores.remove(jugSeleccionado);
        controller.escribirObjeto("jugadores.dat", jugadores);
        //controller.escribirObjeto("estudiantes.dat", estudiantes);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreUsuario.getText();
        String apellido = txtApellido.getText();
        String cedula = txtCedula.getText();
        String login = txtUsuario.getText();

        System.out.println("registra");
        System.out.println(jugadores.size());

        if (!nombre.equals("") && !apellido.equals("") && !cedula.equals("") && !login.equals("")) {
            Jugador jugador = new Jugador(txtNombreUsuario.getText(), txtApellido.getText(), txtCedula.getText(), txtUsuario.getText());

            if (jugadores.size() > 0) {
                for (int i = 0; i < jugadores.size(); i++) {
                    Jugador aux;
                    aux = (Jugador) jugadores.get(i);
                    if (!jugador.getCedula().equals(aux.getCedula()) && !jugador.getLogin().equals(aux.getLogin())) {
                        jugadores.add(jugador);
                        controller.escribirObjeto("jugadores.dat", jugadores);
                        limpiar();
                        llenarCombo();
                        Object objJugadores[] = {jugador.getNombre(), jugador.getApellido(), jugador.getCedula(), jugador.getLogin()};
                        DefaultTableModel model = (DefaultTableModel) tblListaJugadores.getModel();
                        model.addRow(objJugadores);

                        break;
                    } else {

                        JOptionPane.showMessageDialog(rootPane, "JUGADOR YA EXISTE, INGRESE DIFERENTE CEDULA Y USUARIO");
                        txtNombreUsuario.setText(nombre);
                        txtApellido.setText(apellido);
                        txtCedula.setText(null);
                        txtUsuario.setText(null);
                        break;
                    }
                }
            } else {
                if (jugadores.size() == 0) {
                    jugadores.add(jugador);
                    controller.escribirObjeto("jugadores.dat", jugadores);
                    limpiar();
                    llenarCombo();
                    Object objJugadores[] = {jugador.getNombre(), jugador.getApellido(), jugador.getCedula(), jugador.getLogin()};
                    DefaultTableModel model = (DefaultTableModel) tblListaJugadores.getModel();
                    model.addRow(objJugadores);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "AUN NO HA INGRESADO NINGUN JUGADOR");
                }

            }

        } else {

            JOptionPane.showMessageDialog(rootPane, "COMPLETE TODOS LOS CAMPOS DE USUARIO");
        }
        System.out.println(jugadores.size());
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        Jugador jugSeleccionado = (Jugador) cmbListaJugadores.getSelectedItem();
        jugSeleccionado.setNombre(txtNombreUsuario.getText());
        jugSeleccionado.setApellido(txtApellido.getText());
        jugSeleccionado.setCedula(txtCedula.getText());
        jugSeleccionado.setLogin(txtUsuario.getText());

        Object objJugadores[] = {jugSeleccionado.getNombre(), jugSeleccionado.getApellido(), jugSeleccionado.getCedula(), jugSeleccionado.getLogin()};
        DefaultTableModel model = (DefaultTableModel) tblListaJugadores.getModel();
        model.removeRow(cmbListaJugadores.getSelectedIndex());
        jugadores.remove(cmbListaJugadores.getSelectedIndex());
        model.insertRow(cmbListaJugadores.getSelectedIndex(), objJugadores);
        jugadores.add(cmbListaJugadores.getSelectedIndex(), jugSeleccionado);
        controller.escribirObjeto("jugadores.dat", jugadores);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:

        VentanaInicial menu = new VentanaInicial();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Juego().setVisible(true);
            }
        });

        /* Create and display the form */
    }

    public void llenarCombo() {
        if (jugadores.size() > 0) {
            cmbListaJugadores.setEnabled(true);

            cmbListaJugadores.setModel(new javax.swing.DefaultComboBoxModel(jugadores.toArray()));
        } else {
            cmbListaJugadores.setEnabled(false);
        }
    }

    public void llenarGrid() {
        if (jugadores.size() > 0) {
            Jugador est = new Jugador();
            DefaultTableModel model = (DefaultTableModel) tblListaJugadores.getModel();
            for (int i = 0; i < jugadores.size(); i++) {
                est = (Jugador) jugadores.get(i);
                Object jugadorG[] = {est.getNombre(), est.getApellido(), est.getCedula(), est.getLogin()};
                model.insertRow(i, jugadorG);
            }
        }
    }

    public void limpiar() {
        txtNombreUsuario.setText(null);
        txtCedula.setText(null);
        txtApellido.setText(null);
        txtUsuario.setText(null);
        btnCrear.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPanel;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbListaJugadores;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblListaJugadores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
