/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maragarita
 */
public class PanelPersonajes extends javax.swing.JFrame {

    /**
     * Creates new form PanelPersonajes
     */
    ArrayList<Object> listaJugadores = new ArrayList<>();
    Controlador controller = new Controlador();
    ArrayList<Object> personajes = new ArrayList<>();
    ArrayList<Object> batalla = new ArrayList<>();
    
    
    public PanelPersonajes() {
        initComponents();
        // Centering on screen...
        setSize(528, 442);

        Personaje p1 = new Personaje(1300.0, 500.0, "Natsu", "fuego");
        Personaje p2 = new Personaje(1400.0, 700.0, "Azuma", "tierra");
        Personaje p3 = new Personaje(950.0, 400.0, "Wendy", "aire");
        Personaje p4 = new Personaje(1200.0, 600.0, "Juvia", "agua");

        personajes.add(p1);
        personajes.add(p2);
        personajes.add(p3);
        personajes.add(p4);
        
        cmbPersonajes.setModel(new javax.swing.DefaultComboBoxModel(personajes.toArray()));
        cmbPersonajes1.setModel(new javax.swing.DefaultComboBoxModel(personajes.toArray()));

        
        batalla=controller.extraerObjetos("batalla.dat");
        listaJugadores = controller.extraerObjetos("jugadores.dat");
        llenarCombo();
        
        cmbPersonajes.setEnabled(false);
        cmbJugador2.setEnabled(false);
        btnSeleccionarJugador2.setEnabled(false);
        btnSeleccionarJugador1.setEnabled(false);
        cmbPersonajes1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cmbJugador1 = new javax.swing.JComboBox<>();
        cmbJugador2 = new javax.swing.JComboBox<>();
        cmbPersonajes = new javax.swing.JComboBox<>();
        btnSeleccionarJugador1 = new javax.swing.JButton();
        btnBatalla = new javax.swing.JButton();
        btnSeleccionarJugador2 = new javax.swing.JButton();
        btnRegresoRegistro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblPersonaje1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPersonajes1 = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tekton Pro Cond", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 204));
        lblTitulo.setText("POO BATTLE PRO");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(150, 10, 250, 30);

        cmbJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador1);
        cmbJugador1.setBounds(10, 80, 135, 20);

        cmbJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJugador2);
        cmbJugador2.setBounds(370, 80, 130, 20);

        cmbPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonajesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPersonajes);
        cmbPersonajes.setBounds(10, 110, 110, 30);

        btnSeleccionarJugador1.setText("Seleccionar      ");
        btnSeleccionarJugador1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSeleccionarJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarJugador1);
        btnSeleccionarJugador1.setBounds(10, 321, 120, 23);

        btnBatalla.setText("Empezar");
        btnBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatallaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatalla);
        btnBatalla.setBounds(210, 380, 100, 23);

        btnSeleccionarJugador2.setText("Seleccionar ");
        btnSeleccionarJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarJugador2);
        btnSeleccionarJugador2.setBounds(380, 320, 120, 23);

        btnRegresoRegistro.setText("Registro de Jugadores");
        btnRegresoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresoRegistroMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresoRegistro);
        btnRegresoRegistro.setBounds(60, 380, 141, 23);

        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 380, 137, 23);
        getContentPane().add(lblPersonaje1);
        lblPersonaje1.setBounds(10, 160, 150, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Jugador 2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 50, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Jugador 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 120, 30);

        cmbPersonajes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonajes1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPersonajes1);
        cmbPersonajes1.setBounds(370, 110, 110, 30);
        getContentPane().add(lbl);
        lbl.setBounds(360, 150, 150, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPanelPersonajes.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 530, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarJugador2ActionPerformed
        // TODO add your handling code here:
        if(lbl.getText().equals("")){
        
        
        JOptionPane.showMessageDialog(rootPane, "SELECCIONE PERSONAJE");
       btnSeleccionarJugador2.setEnabled(true);
        
      
        }else{
        
        btnSeleccionarJugador1.setEnabled(false);
        btnSeleccionarJugador2.setEnabled(true);
        cmbJugador1.setEnabled(false);
        cmbJugador2.setEnabled(false);
        cmbPersonajes.setEnabled(false);
        cmbPersonajes1.setEnabled(false);
        
        
        
        
        
        btnSeleccionarJugador2.setEnabled(false);
        
        }
        
    }//GEN-LAST:event_btnSeleccionarJugador2ActionPerformed

    private void cmbJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador1ActionPerformed
        // TODO add your handling code here:
        Jugador jugadorselect = (Jugador) cmbJugador1.getSelectedItem();

        btnSeleccionarJugador1.setEnabled(true);
        cmbPersonajes.setEnabled(true);
        
        


    }//GEN-LAST:event_cmbJugador1ActionPerformed

    private void btnRegresoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresoRegistroMouseClicked
        // TODO add your handling code here:
        Juego jugadores = new Juego();
        jugadores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresoRegistroMouseClicked

    private void btnSeleccionarJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarJugador1ActionPerformed
        // TODO add your handling code here:
        
        if(lblPersonaje1.getText().equals("")){
        
        
        JOptionPane.showMessageDialog(rootPane, "SELECCIONE PERSONAJE");
       btnSeleccionarJugador1.setEnabled(true);
        
      
        }else{
        
        Jugador jugSeleccionado = (Jugador) cmbJugador1.getSelectedItem();
        Personaje pj= (Personaje) cmbPersonajes.getSelectedItem();
        ClsJuego batalla1= new ClsJuego(jugSeleccionado,pj);
        batalla.add(batalla1);
        controller.escribirObjeto("batalla.dat", batalla);
        
        btnSeleccionarJugador1.setEnabled(false);
        btnSeleccionarJugador2.setEnabled(true);
        cmbJugador1.setEnabled(false);
        cmbJugador2.setEnabled(true);
        cmbPersonajes.setEnabled(false);
        cmbPersonajes1.setEnabled(true);
       
        }
        
        
    }//GEN-LAST:event_btnSeleccionarJugador1ActionPerformed

    private void cmbJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador2ActionPerformed
        // TODO add your handling code here:
        Jugador jugadorselect = (Jugador) cmbJugador1.getSelectedItem();

        btnSeleccionarJugador1.setEnabled(false);

    }//GEN-LAST:event_cmbJugador2ActionPerformed

    private void cmbPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonajesActionPerformed
        // TODO add your handling code here:
        Personaje personajeselect = (Personaje) cmbPersonajes.getSelectedItem();
        
        
        
        String nombre=personajeselect.getNombre();
        
        if (nombre.equals("Natsu")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Natsu.jpg"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(),Image.SCALE_DEFAULT));
            lblPersonaje1.setIcon(icono);
            lblPersonaje1.setText("Natsu");
        
        }else if (nombre.equals("Azuma")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Azuma.jpg"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(),Image.SCALE_DEFAULT));
            lblPersonaje1.setIcon(icono);
            lblPersonaje1.setText("Azuma");
        
        }else if (nombre.equals("Juvia")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Juvia.png"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(),Image.SCALE_DEFAULT));
            lblPersonaje1.setIcon(icono);
            lblPersonaje1.setText("Juvia");
        }else if (nombre.equals("Wendy")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Wendy.png"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lblPersonaje1.getWidth(), lblPersonaje1.getHeight(),Image.SCALE_DEFAULT));
            lblPersonaje1.setIcon(icono);
            lblPersonaje1.setText("Wendy");
        }
        
        
        
        
        

    }//GEN-LAST:event_cmbPersonajesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaInicial menu = new VentanaInicial();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbPersonajes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonajes1ActionPerformed
        // TODO add your handling code here:
        Personaje personajeselect = (Personaje) cmbPersonajes1.getSelectedItem();
        
        
        
        String nombre=personajeselect.getNombre();
        
        if (nombre.equals("Natsu")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Natsu.jpg"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
            lbl.setIcon(icono);
            lbl.setText("Natsu");
        
        }else if (nombre.equals("Azuma")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Azuma.jpg"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
            lbl.setIcon(icono);
            lbl.setText("Azuma");
        
        }else if (nombre.equals("Juvia")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Juvia.png"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
            lbl.setIcon(icono);
            lbl.setText("Juvia");
        }else if (nombre.equals("Wendy")){
            ImageIcon dir= new ImageIcon(getClass().getResource("/Imagenes/Wendy.png"));
            ImageIcon icono= new ImageIcon(dir.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_DEFAULT));
            lbl.setIcon(icono);
            lbl.setText("Wendy");
        }
        
        
    }//GEN-LAST:event_cmbPersonajes1ActionPerformed

    private void btnBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatallaActionPerformed
        // TODO add your handling code here:
        Batalla versus = new Batalla();
        versus.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPersonajes().setVisible(true);
            }
        });
    }

    public void llenarCombo() {
        if (listaJugadores.size() > 0) {
            cmbJugador1.setEnabled(true);
            cmbJugador2.setEnabled(true);

            cmbJugador1.setModel(new javax.swing.DefaultComboBoxModel(listaJugadores.toArray()));
            cmbJugador2.setModel(new javax.swing.DefaultComboBoxModel(listaJugadores.toArray()));

        } else {
            cmbJugador1.setEnabled(false);

            cmbJugador2.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalla;
    private javax.swing.JButton btnRegresoRegistro;
    private javax.swing.JButton btnSeleccionarJugador1;
    private javax.swing.JButton btnSeleccionarJugador2;
    private javax.swing.JComboBox<String> cmbJugador1;
    private javax.swing.JComboBox<String> cmbJugador2;
    private javax.swing.JComboBox<String> cmbPersonajes;
    private javax.swing.JComboBox<String> cmbPersonajes1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblPersonaje1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
